# Change these first
owner: fr0st-iwnl  # Your GitHub organization or username, where this repository lives
repo: status.fr0st.xyz # The name of this repository

sites:
  - name: search.fr0st.xyz
    url: https://search.fr0st.xyz/
    expectedStatusCodes:
      - 200
      - 201
      - 202
  - name: data.fr0st.xyz
    url: https://data.fr0st.xyz/
    expectedStatusCodes:
      - 200
      - 201
      - 202
  - name: memos.fr0st.xyz
    url: https://memos.fr0st.xyz/
    expectedStatusCodes:
      - 200
      - 201
      - 202
  - name: fr0st.xyz
    url: https://fr0st.xyz/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.fr0st.xyz
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: fr0st Status
  introTitle: "**fr0st Status** — Real-time uptime for my projects and services."
  introMessage: This page shows live status for all my important sites and services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
